### ISSUE TITLE
Cross Origin Video Not Working

### ISSUE THREAD

**Issue by tmugavero** [flimshaw/Valiant360#10]
Awesome project and thanks for putting it together.  We've been testing with it a bit and it works perfectly in chrome (haven't tested in others.)  As you may be aware, it appears that CORS is a problem on video.  We've tried setting crossOrigin = 'anonymous' on the video object, THREE.ImageUtils.crossOrigin = "anonymous", and various other things.  This is the error:

Uncaught SecurityError: Failed to execute 'texImage2D' on 'WebGLRenderingContext': The video element contains cross-origin data, and may not be loaded. 

It appears that we aren't the only ones experiencing this problem with CORS and video/canvas/WebGL (across a number of different projects and threads on StackOverflow), but wondering if you've stumbled across a fix or if you've found it's just impossible at the moment without some kind of proxy type hack to make things look like the same domain?

**Comment by zlot** [comment]
Hi Tony and Charlie,

I've submitted pull request #20 which adds an option for a crossOrigin keyword, defaulting to 'anonymous'. This fixes problems I was having when using images or video I was sourcing from a cdn. 

I'm a bit late to the party however—Tony I see you've made big strides with littlstar/Axis framework :)
