### ISSUE TITLE
jumps to a low fov when scrolling

### ISSUE THREAD

**Issue by michellecruz** [flimshaw/Valiant360#31]
this is a great plugin. simple & easy to use. I just have one issue - I have my initial fov set at 135 and it looks like there's a glitch when I try scrolling. It instantly jumps to a low fov, around 10-15.

**Comment by janthoma** [comment]
Add this after Line 112

```
fovMin: 3,
fovMax: 160,
```

this after line 165

```
this._fovMin = this.options.fovMin
this._fovMax = this.options.fovMax
```
replace on line 410

```
var fovMin = 3;
var fovMax = 100;
```

with this

```
var fovMin = this._fovMin;
var fovMax = this._fovMax;
```

and finally replace on Line 419

```
this._camera.setLens(this._fov);
event.preventDefault();
```

with this

```
this._camera.fov = this._fov;
this._camera.updateProjectionMatrix();
```

THREE.js setLens uses focal length in mm not FOV

**Comment by flimshaw** [comment]
I believe @zlot's recent updates to v0.4.0 implements this fix
