### ISSUE TITLE
How to create a panorama like equirectangular-bathroom-tile.

### ISSUE THREAD

**Issue by SanjeethKumarTS** [flimshaw/Valiant360#38]
I have plans to use Valiant360 in my project.Can anyone please tell how the equirectangular-bathroom-tile is created.I have tried creating a panorama on my phone and tried to use it.But the **360 view is distorted**.Why is the image present in the Example app so clear?**How do i create one such image**.

Please help.
Thank you!

**Comment by SanjeethKumarTS** [comment]
@flimshaw pls help

**Comment by flimshaw** [comment]
Hello there!  My version of that image was rendered in Blender using their equirectangular/panorama camera setting.  The way Valiant360 works is to take a texture and draw it onto a sphere in 3D space, then a virtual camera is placed in the middle of that sphere, and it simulates being surrounded on all sides by video.  All sphere textures should be a 2:1 aspect ratio, exactly twice as wide as they are tall, and your videocard will be happiest if the texture's dimensions are a power of 2.  So, make sure your image is one of these resolutions: 1024x512, 2048x1024, 4096x2048.

Hope this helps, if you post the image you're using that looks distorted, maybe I can give you some more advice.
